import type { Metadata } from "next";
import "./globals.css";
import { Main } from "next/document";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";


export const metadata: Metadata = {
  title: "Digital Solutions",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
          <body>
            <Navbar />
            <main className="relative overflow-hidden">
            {children}
            </main>
            <Footer />
          </body>
    </html>
  );
}
